### ISSUE TITLE
Building CMake 3.0.2

### ISSUE THREAD

**Issue by InnocentBug** [MICCoM/SSAGES-public#1]
Working with CMake version 3.0.2 I get the following problem:

CMake Error at CMakeLists.txt:121 (CONFIGURE_ENGINE):
  Unknown CMake command "CONFIGURE_ENGINE".

You request CMake version 2.8.8, so I guess it should work in principle.

**Comment by hsidky** [comment]
Hi, 

Can you share the cmake command you called? It looks like you may not have specified an engine.

**Comment by InnocentBug** [comment]
Hi,

you are right. I missed to set an engine. Setting one fixed it.
Thanks for the quick response.

(For people in the future a warning for no engine might help.)
