### ISSUE TITLE
Segmentation fault when using ANN sampling.

### ISSUE THREAD

**Issue by HanatoK** [MICCoM/SSAGES-public#9]
I have tried the ANN sampling with the NANMA(alanine dipeptide) system and gotten a segfault. The MD engine is GROMACS and SSAGES is the latest git version.
Error log: https://gist.github.com/HanatoK/c88ff5bf68a6491172ffe2928342caf5
Input file: https://gist.github.com/HanatoK/cb67ee0917610d2a2af48efc4f937aea

**Comment by mquevill** [comment]
There is a chance that your build may have gotten messed up if you changed versions of GROMACS or something. I was able to run your input file with GROMACS 2018.1 (`cmake .. -DGROMACS=2018.1`) without encountering a segfault.

Try recompiling from clean with
```bash
cd build
make clean
make
```

Or, you can just delete the build directory outright and start from the beginning, including downloading GROMACS 2018.1 again, with
```bash
rm -r build
mkdir build
cd build/
cmake .. -DGROMACS=2018.1 #include other CMake flags that you need
make
```

If these don't fix your issues, please let me know what error messages you are still receiving and we will try to address them.

**Comment by HanatoK** [comment]
Thanks for your reply. I tried the same input on another machine and the ANN sampling worked. Maybe there are some issues about the CUDA or GROMACS configurations.
